# Generated by Django 5.2.3 on 2025-06-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_graph', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='fotmob_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
