# Generated by Django 5.2.3 on 2025-06-13 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_graph', '0002_player_fotmob_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='successful_passes',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='data',
            name='touches',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
