# Generated by Django 5.2.3 on 2025-06-16 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('football_graph', '0003_alter_data_successful_passes_alter_data_touches'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='market_value',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
